[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msentity"
version = "0.1.0"
description = ""
authors = [
    { name = "Motohiro Ogawa" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "tqdm",
    "numpy",
    "pandas",
    "h5py",
    "pyarrow"
]

[project.optional-dependencies]
gui = [
    "gradio>=5.50,<6",
    "gradio-msentityviewer @ https://github.com/MotohiroOGAWA/msentity/releases/download/gradio-msentityviewer-v0.1.0/gradio_msentityviewer-0.1.0-py3-none-any.whl",
]
docs = [
    "sphinx>=8",
    "furo",
    "sphinx-autodoc-typehints",
    "myst-parser",
    "myst-nb",
    "jupyter-sphinx>=0.5",
]

[project.scripts]
msentity = "msentity.cli.main:main"

[tool.setuptools.packages.find]
include = ["msentity*"]

[tool.mypy]
files = ["msentity"]
show_error_codes = true
strict = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[tool.pytest.ini_options]
testpaths = ["tests"]
